language: node_js
node_js:
- lts/carbon

cache:
  directories:
  - node_modules

before_install:
  - git lfs pull

script:
- yarn build

deploy:
  - provider: s3
    skip_cleanup: true
    access_key_id: AKIAJ7ZV2Y6ZKBXNJWZQ
    secret_access_key:
      secure: "Ie8KaUHsDuoJD9kVTA2nhQUEvsFMeWMd/lr4L8UVpPr6MvftTnVhagwgJB/cpR4GKfbEdGqfljnR7Ouup93yMmus+FLEhFOjtLtzJDyW0jnyw7MhATeoqRlnsscKsgobdpMLE0EGdq3BBLkKg80AJSiR8Lnz0xq6vhlUL5YnGexqZsVcxSi3L4exiFpbiWGvsHl1QXsW6jm5k3eX7P7opW5yFFfHqaTUXpMGjYk4sucgd4QvFw4ACbdJX5zSOCauG9DsZcmnwEc//8pjxngylFITlju6cldtezTTuvDSun/cspFqjMa/MqcZu1Fc5KTf0er5tGmGCscPB6c1Fx8DAchePwmscz/AdgjcI6x3h9BmE/23qh3WoNBWw+DjlUMQCIMN3vdkrlELG4a2MhrsZBw2b6s2VXVEkFMDg7RIWdPc+0prdpTJDokwIstttggSkZz2TRya/ZkJN0Huxr+tUCcDEdpTl3KibwDLZ/aA+Amr1Mk8PddGnNyDchh9Cl3ECqw0XZaNFNBraBguqDxugllHEIoIZQHPfCARfdlFAag2d0rKT+7Z2dXknfdqtx3HuIUfS9an5hLe31sqAoPypEG4OYvLFDF5sRkjJqa+9WOQOT3plI8ouVsDH+K5nfxdebKm9MkoV++yDaFjZVwktJocyzy8Yv7b1W0Y4/+9tJ8="
    bucket: contextubot.net
    acl: public_read
    local_dir: build
    on:
      branch: develop

notifications:
  irc: chat.freenode.net#contextubot
  slack:
    rooms:
      secure: KuDr6gQNRwzxfvW1TlrYJxoYErAFVdtj/UgVDw7484J/3XviXZ5hA2znPA1AoPlxI/YGMhdVw1VOUPUFMBBsKKPnyBIAMJs4mE5xWalCoenlECSxc/P1X9/toRTR0sJiyWSLSiJejmsjQ2xqXJT6nI8ZulU8JUTd2TdrjJG9uy6yWhC4z4+sTkvu1Jwy/hyz8G9EpAL1cemrLxC1ebzK0Px2oX+6annWT6dsdZLbOaYV/gWon/QSARTqJEDIe6Ukq9eif4bgjpFvJEBj8pxbhDGpiqRT5+GcKFmx2Ftq4cQZPalQawn5gnuRDDTD8FqXWrGMeRs7x0SqaPgXQo8dO5D4SxseXQDjZpfBNmrj74trnFgfUs4Q/nx8MRFCqbgCqIA+dN4FA6T0+17t7uMw1SJhN+rVGagF4ypUGFFH+4adl6wpLYFWO5s/9gDCh2ln79fVwjPWYveV1FCLXj4GrI38UH7oCocS8aCrJMJlLmCUGbI2hzn5nyVWoteUGlLziFnfUUxzxPhXSlg3FX7QyVyDGK4+q3t27GbfxkBzDoj6sBPub8Ys7Td3sK7qds1sdv0h9Cr1oxWHW12vno8E/W+6wJ+z1khJpJ5tdX0aRMsYP9URVxLMGwRKbkb7XGtZYEtHyh0NWCgKALcdix3eoo6wRBEYxTTV7GSiyoyIXaE=
