custom:
  logRetentionInDays: 5
  pythonRequirements:
    dockerizePip: true
    slim: true
    zip: true
    useDownloadCache: true
    useStaticCache: true

service: contextubot

provider:
  name: aws
  tags:
    project: contextubot
  
  runtime: python3.6
  timeout: 300
  
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - 's3:*'
      Resource:
        Fn::Join:
          - ''
          - - 'arn:aws:s3:::data.contextubot.net'
        
  environment:
    BUCKET_NAME: 'data.contextubot.net'


package:
  individually: true
  exclude:
    - '*/**'

functions:
  extract:
    handler: extract-audio/handler.extract
    module: extract-audio
    package:
      include:
        - 'extract-audio/*.py'
        - 'extract-audio/.requirements.zip'    
        - 'extract-audio/ffmpeg/*'
  create:
    handler: handler.create
    module: audfprint
    package:
      include:
        - 'audfprint/*.py'
        - 'audfprint/.requirements.zip'
  match:
    handler: handler.match
    module: audfprint
    package:
      include:
        - 'audfprint/*.py'
        - 'audfprint/.requirements.zip'

plugins:
  - serverless-python-requirements
  - serverless-plugin-log-retention
