service:
  name: contextubot-worker

provider:
  name: aws
  region: us-east-1

  runtime: python3.6
  timeout: 300
  stage: dev
  tracing: true

  tags:
    project: contextubot

  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - 's3:*'
        # - 's3:PutBucketNotification'
      Resource:
        Fn::Join:
          - ''
          - - 'arn:aws:s3:::data.contextubot.net'
    - Effect: 'Allow'
      Action:
        - 's3:*'
      Resource:
        Fn::Join:
          - ''
          - - 'arn:aws:s3:::data.contextubot.net/*'
    - Effect: 'Allow'
      Action:
        - 'xray:PutTraceSegments'
        - 'xray:PutTelemetryRecords'
      Resource:
        - "*"

  environment:
    BUCKET_NAME: 'data.contextubot.net'
    PUBNUB_PUB: ${ssm:/contextubot/pubNubPublishKey}
    PUBNUB_SUB: ${ssm:/contextubot/pubNubSubscribeKey}
    PUBNUB_SECRET: ${ssm:/contextubot/pubNubSecretKey}


package:
  individually: true
  exclude:
    - '*/**'

functions:
  create:
    handler: handler.fingerprint
    module: audfprint
    events:
      - existingS3:
          bucket: 'data.contextubot.net'
          events:
            - s3:ObjectCreated:*
          rules:
            - prefix: wave/
            - suffix: .wav
    package:
      include:
        - 'audfprint/*.py'
        - 'audfprint/.requirements.zip'
  match:
    handler: handler.match
    module: audfprint
    package:
      include:
        - 'audfprint/*.py'
        - 'audfprint/.requirements.zip'

plugins:
  - serverless-python-requirements
  - serverless-plugin-log-retention
  - serverless-stage-manager
  - serverless-plugin-existing-s3
  - serverless-plugin-tracing

custom:
  stages:
    - dev
    - staging
    - prod
  logRetentionInDays: 5
  pythonRequirements:
    dockerizePip: true
    slim: true
    zip: true
    useDownloadCache: true
    useStaticCache: true
